services:
  indieweb:
    build: .
    container_name: indieweb_site
    restart: always
    network_mode: host
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - /home/pi/data:/data
    ports:
      - "127.0.0.1:8080:8080"
    restart: always