services:
  indieweb:
    build: .
    container_name: indieweb_site
    restart: always
    ports:
      - "80:80"
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - /home/pi/data:/data
    restart: always