[build]
  command = "npm run build"
  publish = "."

[build.processing]
  skip_processing = true

[[redirects]]
  from = "/blog"
  to = "/blog/_site/index.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/blog/_site/:splat"
  status = 200

[[redirects]]
  from = "/photos"
  to = "/photos/_site/index.html"
  status = 200

[[redirects]]
  from = "/photos/*"
  to = "/photos/_site/:splat"
  status = 200